name: Build iOS (no-sign)

on:
  workflow_dispatch:
  push:
    branches:
      - 'smart-cache'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Build-iOS:
    runs-on: macos-latest
    env:
      FLUTTER_VERSION: 3.44.8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'master'
          cache: true

      - name: Output Flutter Version
        run: flutter --version

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          key: ios-pods-${{ hashFiles('ios/Podfile.lock') }}
          path: ios/Pods

      - name: Flutter Pub Get
        run: |
          git config --global core.longpaths true
          flutter pub get

      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Get app version
        id: get_version
        shell: bash
        run: |
          echo "version=$(head -n 5 pubspec.yaml | tail -n 1 | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

      - name: Build iOS (unsigned)
        run: |
          flutter precache --ios
          cd ios
          pod update
          cd ..
          flutter build ios -t lib/src/main.dart --release --no-codesign
          sh thin-payload.sh build/ios/iphoneos/*.app
          cd build
          mkdir -p Payload
          mv ios/iphoneos/*.app Payload
          zip -9 JHenTai_${{ steps.get_version.outputs.version }}_nosign.ipa -r Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-iOS-nosign
          path: build/*.ipa
          if-no-files-found: error
